FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    gcc \
    make \
    libtool \
    libc6-dev \
    pkg-config \
    build-essential \
    cmake \
    zip \
    unzip \
    ca-certificates \
    autoconf \
    automake \
    autopoint \
    gettext \
    && apt-get clean && rm -rf /var/lib/apt/lists/*